### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by laheller** [skywatcher-pacific/skywatcher_open#1]
Hi @lucemia 

Where is that **Astrolib** which is referenced at **using** section in the below file:
_BasicApi_CS\Type\AstroMisc.cs_

**Comment by lucemia** [comment]
long time ago.. should be this one https://github.com/skywatcher-pacific/android-app/tree/master/AstroLib

**Comment by laheller** [comment]
@lucemia 
Thank you man! You saved me!!! :)

BTW, what about the development at SkyWatcher? Are you working for them or?
They somehow doesn't publish any SDK or something like that.
I asked them some weeks ago whether it is possible to query the database stored in Hand Controller of goto mounts via the serial interface. For example to get RA/DEC coordinates of Polaris or similar queries.
At least they answered. Short answer was: NO! :D 

Regards,

Ladislav Heller

**Comment by laheller** [comment]
@lucemia @jnl16 
Please guys, give me link to the **astrolib**! 
I really need that library for my telescope project!
I am even able to pay for that library!
The link @lucemia sent me in the above comment is unfortunately not valid :-(

**Comment by lucemia** [comment]
@jnl16 Do you use the astrolib recently?
 I remember there used to have a compiled dll file for astrolib for download...

**Comment by lucemia** [comment]
@laheller 

I checked the BasicApi_CS project, it actually don't use AstroMisc and AstroLib. You can delete these files.  Otherwise please specify what feature/function you are looking for?

**Comment by laheller** [comment]
@lucemia
I was looking for calculations for **Julian Day**, **Greenwich Mean Sidereal Time**, **Local Sidereal Time**, RA/DEC -> ALT/AZM conversion, etc. But I have found already a working solution for them (good old Wikipedia always helps :) ) so I think this "issue" can be closed.
I am developing my own Android application which makes the above calculations and also talks to **SynScan** Hand Controller. And also it searches for celestial object parameters in online databases.
BTW it is possible somehow **query** the hand controller's **internal database** and get information about the stored objects? For example query RA/DEC coordinates for Polaris.

**Comment by lucemia** [comment]
@laheller 
As far as I know, there is no such utils be able to query information from hand controller yet...
